/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Game types for One Minute Boss (一分钟老板)

export interface CompanyStats {
  finance: number;      // 财务 (0 - 100)
  employee: number;     // 员工满意度 (0 - 100)
  reputation: number;   // 舆论/公信度 (0 - 100)
  progress: number;     // 目标完成度 (0 - 100)
  risk: number;         // 风险指数 (0 - 100)
}

export interface GameOption {
  text: string;         // Option text
  consequence: string;  // Brief summary of what the choices entail (absurd teaser)
}

export interface GameEvent {
  id: string;
  roundNum: number;
  storySegment: string;      // The narrative text generated by AI
  options: GameOption[];     // Three-choice options
  newsHeadline?: string;     // Simulated PR hot search or newspaper headline
  commentBox?: {             // Fun community/internal responses
    source: 'employee' | 'shareholder' | 'netizen' | 'competitor';
    author: string;
    text: string;
  };
  isClimax: boolean;         // True if this is the final/high-tension round
}

export interface GameSetup {
  companyName: string;
  targetGoal: string;
  planSummary: string;
  personality: string;       // Boss profile (e.g. "妄想狂", "无良资本家", "佛系梦想家")
  type: string;              // Industry type
  hiddenThreat: string;      // A secret doom factor
  initialEvent: GameEvent;   // The first event to show
}

export interface DecisionResult {
  stats: CompanyStats;
  consequenceFeedback: string; // Dynamic text summarizing what happened after choosing
  nextEvent: GameEvent | null; // The next event OR null if the game is over
  isGameOver: boolean;
  gameOverReason?: 'finance_ruin' | 'strike' | 'pr_disaster' | 'jailed' | 'timeout' | 'completed';
}

export interface GameSettlement {
  title: string;             // Absurd title awarded (e.g., "仙女座奶茶收割者")
  grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'F'; // Corporate performance grade
  summary: string;           // Humorous post-mortem story
  finalStats: CompanyStats;
  statsHistory: CompanyStats[];
  achievements: string[];    // Absurd achievements unlocked this round
  suggestedChallenge: string; // Encouraging retry direction
  shareMarkdown: string;     // Beautiful clipboard-copyable text
}

export interface HistoryItem {
  id: string;
  companyName: string;
  targetGoal: string;
  title: string;
  grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'F';
  timestamp: string;
  outcomeSummary: string;
}
